name: flutter_bcrypt
description: A flutter bcrypt hashing plugin delegating to android &#x2F; ios native implementations.
version: 1.0.5
author: Jeroen Trappers <jeroen@appmire.be>
homepage: https://github.com/jeroentrappers/flutter_bcrypt

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.appmire.flutter_bcrypt
    pluginClass: FlutterBcryptPlugin

